services:
  proxy:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./proxy/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./proxy/nginx-run:/bin/nginx-run:rw
    depends_on:
      - api
      - webapp
    environment:
      WEBAPP_HOST: ${WEBAPP_HOST:-webapp}
      WEBAPP_PORT: ${WEBAPP_PORT:-5173}
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-8080}
    command: "nginx-run"
  
  webapp:
    image: arm64v8/node:lts-slim
    working_dir: /app
    volumes:
      - ./webapp:/app
    command: sh -c "npm install && npm run build && npm run dev"
    ports:
      - ${WEBAPP_PORT:-5173}:${WEBAPP_PORT:-5173}
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://${API_HOST:-api}:${API_PORT:-8080}
    networks:
      default:
        aliases:
          - "${WEBAPP_HOST:-webapp}"
  api:
    build: api
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - ${API_PORT:-8080}:${API_PORT:-8080}
    depends_on:
      - db
    networks:
      default:
        aliases:
          - "${API_HOST:-api}"
  db:
    container_name: ${DB_HOST:-db}
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - "${DB_HOST:-db}"

volumes:
  db_data: {}